version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "moment-timezone"
      - dependency-name: "google-libphonenumber"  